### PR TITLE
Updated TensorFlow-GPU Dockerfile to v1.1.

### PR DESCRIPTION
**Pull request by sebastianbk**
Title is pretty self-explanatory. :smile:

### CODE REVIEW

**Comment by alfpark** [comment]
@sebastianbk TensorFlow hasn't officially reached 1.1 yet. Do you mind if we hold off merging until it exits rc? We'll probably need to review the upstream Dockerfile for any changes as well.

**Comment by sebastianbk** [comment]
Sure. :smile:

By the way, I looked into it a little bit. Is the only "optimization" for NC-series VMs the removal of some of the supported CUDA version numbers? That's the only difference I can find when comparing to the Dockerfile in the official TensorFlow repo.

**Comment by alfpark** [comment]
The Dockerfile might have changed between 1.0 and 1.1. The `TF_CUDA_COMPUTE_CAPABILITIES` should have been expanded to include K80/M60 specific SM/Compute capability. It looks like they added Pascal series compute to the build. Once TF reaches 1.1 we'll do a full audit of the build and either drop the custom build or bring it up to date.

**Comment by alfpark** [comment]
Docker-related files removed from TensorFlow recipes; moving to stock Docker images as they are "close enough."

**Pull request closed without merging**
